version: "3.9"

services:
  smart-work:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    volumes:
      - ./sqlite_db:/SmartWork/database
    ports:
      - "8002:8000"
    restart: unless-stopped
    environment:
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=${DEBUG}
